### ISSUE TITLE
[FEATURE] Add a grapheme splitter

### ISSUE THREAD

**Issue by l-alexandrov** [talkroute/message-segment-calculator-php#2]
## Overview
We need to find an appropriate library that we could use for grapheme splitting. If a suitable could not be found, such have to be implemented.

## Acceptance Criteria
- [ ] It have to be a standalone class
- [ ] It have to be able to accept a string and split it to an array of grapheme clusters (one string each)

**Comment by erichowey** [comment]
Does it need to count the graphemes as well or are we just going to count the array? Looking at the 
message-segment-calculator library, they seem to be using the `countGraphemes` function of the library as well.

It looks like the only real choice for php in this matter is php's internal grapheme functions:

https://www.php.net/manual/en/ref.intl.grapheme.php

**Comment by erichowey** [comment]
This appears to work:

```php
<?php
<?php

//$string = 'Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞';
//$string = 'अनुच्छेद';
$string = '🌷🎁💩😜👍🏳️‍🌈';

$length = grapheme_strlen($string);

$array = [];
for ($i=0; $i<=$length-1; $i++) {
	$array[] = grapheme_substr($string, $i, 1);
}

var_dump($length);
var_dump($array);

**Comment by l-alexandrov** [comment]
> Does it need to count the graphemes as well or are we just going to count the array? Looking at the message-segment-calculator library, they seem to be using the `countGraphemes` function of the library as well.
> 
> It looks like the only real choice for php in this matter is php's internal grapheme functions:
> 
> https://www.php.net/manual/en/ref.intl.grapheme.php

I cannot seem to find the usage. Would you please send me a reference for the `countGraphemes` function uses? Anyway, it would be always useful to have graphemes counting function too.

**Comment by erichowey** [comment]
You're correct. I can't find it either. I must have been confused.
However, it appears php actually has methods for handling this built into it, which is rather surprising. I think implementing both functions shouldn't be a problem using functions from the snippet above.
